"""Lisbon Metro stations — guess the station from its art/architecture."""

STATIONS = [
    "Aeroporto", "Encarnação", "Moscavide", "Oriente", "Cabo Ruivo",
    "Olivais", "Chelas", "Bela Vista", "Olaias", "Alameda",
    "Saldanha", "São Sebastião", "Parque", "Marquês de Pombal",
    "Avenida", "Restauradores", "Rossio", "Martim Moniz", "Intendente",
    "Anjos", "Arroios", "Baixa-Chiado", "Cais do Sodré",
    "Terreiro do Paço", "Santa Apolónia", "Campo Grande",
    "Cidade Universitária", "Entre Campos", "Campo Pequeno",
    "Rato", "Laranjeiras", "Jardim Zoológico", "Praça de Espanha",
    "Telheiras", "Lumiar", "Quinta das Conchas", "Amadora Este",
    "Alfornelos", "Pontinha", "Carnide", "Colégio Militar",
    "Alto dos Moinhos", "Picoas",
]

# Wikimedia Commons filenames with station art/architecture photos
COMMONS_FILES = {
    "Aeroporto": "Metro de Lisboa - Estação Aeroporto (8176857326).jpg",
    "Encarnação": "Estação de Metro Encarnação.jpg",
    "Moscavide": "Metropolitano de Lisboa - Moscavide.jpg",
    "Oriente": "MetroOriente4.JPG",
    "Cabo Ruivo": "MetroLisboa02.JPG",
    "Olivais": "MetroOlivais3.JPG",
    "Chelas": "MetroChelas2.JPG",
    "Bela Vista": "Bela Vista Metro station, Lisbon.jpg",
    "Olaias": "Metro de Lisboa - Estação Olaias (8175721609).jpg",
    "Alameda": "Lisboa Metro station Alameda II Linha Vermelha.JPG",
    "Saldanha": "Metro Lisboa Lisbon Saldanha.jpg",
    "São Sebastião": "Lisbon Lisboa Metro Sao Sebastiao atrio sul.jpg",
    "Parque": "Metro Lisboa Lisbon station Parque linha azul.jpg",
    "Marquês de Pombal": "Entrada marques de pombal metro lisboa.jpg",
    "Avenida": "Metro station Lisboa Avenida platform.jpg",
    "Restauradores": "Restauradores metro station (40480632731).jpg",
    "Rossio": "RossioMetroLx3.JPG",
    "Martim Moniz": "Metro Lisboa Martim Moniz.jpg",
    "Intendente": "Estação Intendente.jpg",
    "Anjos": "AnjosMetroLx4.JPG",
    "Arroios": "ArroiosMetroLx5.JPG",
    "Baixa-Chiado": "Estacao baixa chiado metro lisboa 2.jpg",
    "Cais do Sodré": "Cais do Sodré metro station (41758535384).jpg",
    "Terreiro do Paço": "Metro Lisboa Lisbon Terreiro do Paco platforms.jpg",
    "Santa Apolónia": "SantaApoloniaMetroLx2.JPG",
    "Campo Grande": "CampoGrandeMetroLx1.JPG",
    "Cidade Universitária": "Metro station Cidade Universitária (Lisboa) 4.jpg",
    "Entre Campos": "EntreCamposMetroLx7.JPG",
    "Campo Pequeno": "486-0372 metro lisboa - campo pequeno.JPG",
    "Rato": "RatoMetroLx5.JPG",
    "Laranjeiras": "Metro Lisboa Lisbon station Laranjeiras.jpg",
    "Jardim Zoológico": "Jardim Zoológico Metro Station (2) 2005.12.29.jpg",
    "Praça de Espanha": "Metro station Lisboa Lisbon Praca de Espanha azulejos.jpg",
    "Telheiras": "Estação de Telheiras.jpg",
    "Lumiar": "Metro Lisboa Lumiar.jpg",
    "Quinta das Conchas": "Lisboa Metro station Quinta das Conchas platforms.JPG",
    "Amadora Este": "Metro Lisboa Amadora Este.jpg",
    "Alfornelos": "Metro station Lisboa Lisbon Alfornelos.jpg",
    "Pontinha": "Metro Lisboa January 2015-2a.jpg",
    "Carnide": "MetroCarnide1.JPG",
    "Colégio Militar": "Metro station Lisboa Lisbon Colegio Militar Luz Metro logo.jpg",
    "Alto dos Moinhos": "Metro Lisboa Alto dos Moinhos.jpg",
    "Picoas": "Picoas entrance.jpg",
}

# Metro lines
LINES = {
    "Aeroporto": "Vermelha",
    "Encarnação": "Vermelha",
    "Moscavide": "Vermelha",
    "Oriente": "Vermelha",
    "Cabo Ruivo": "Vermelha",
    "Olivais": "Vermelha",
    "Chelas": "Vermelha",
    "Bela Vista": "Vermelha",
    "Olaias": "Vermelha",
    "Alameda": "Vermelha / Verde",
    "Saldanha": "Amarela / Vermelha",
    "São Sebastião": "Azul / Vermelha",
    "Parque": "Azul",
    "Marquês de Pombal": "Azul / Amarela",
    "Avenida": "Azul",
    "Restauradores": "Azul",
    "Rossio": "Verde",
    "Martim Moniz": "Verde",
    "Intendente": "Verde",
    "Anjos": "Verde",
    "Arroios": "Verde",
    "Baixa-Chiado": "Azul / Verde",
    "Cais do Sodré": "Verde",
    "Terreiro do Paço": "Azul",
    "Santa Apolónia": "Azul",
    "Campo Grande": "Amarela / Verde",
    "Cidade Universitária": "Amarela",
    "Entre Campos": "Amarela",
    "Campo Pequeno": "Amarela",
    "Rato": "Amarela",
    "Laranjeiras": "Azul",
    "Jardim Zoológico": "Azul",
    "Praça de Espanha": "Azul",
    "Telheiras": "Verde",
    "Lumiar": "Amarela",
    "Quinta das Conchas": "Amarela",
    "Amadora Este": "Azul",
    "Alfornelos": "Azul",
    "Pontinha": "Azul",
    "Carnide": "Azul",
    "Colégio Militar": "Azul",
    "Alto dos Moinhos": "Azul",
    "Picoas": "Amarela",
}
