"""Portuguese monuments and landmarks."""

MONUMENTOS = [
    "Torre de Belém",
    "Mosteiro dos Jerónimos",
    "Palácio da Pena",
    "Castelo de São Jorge",
    "Ponte 25 de Abril",
    "Sé de Lisboa",
    "Universidade de Coimbra",
    "Convento de Cristo",
    "Mosteiro de Alcobaça",
    "Mosteiro da Batalha",
    "Palácio da Bolsa",
    "Sé do Porto",
    "Ponte Dom Luís I",
    "Santuário do Bom Jesus do Monte",
    "Castelo de Guimarães",
    "Torre dos Clérigos",
    "Aqueduto das Águas Livres",
    "Palácio Nacional de Mafra",
    "Palácio Nacional de Sintra",
    "Castelo de Almourol",
    "Castelo de Óbidos",
    "Fortaleza de Sagres",
    "Sé de Braga",
    "Ruínas de Conímbriga",
    "Templo Romano de Évora",
]

LOCALIZACOES = {
    "Torre de Belém": "Lisboa",
    "Mosteiro dos Jerónimos": "Lisboa",
    "Palácio da Pena": "Sintra",
    "Castelo de São Jorge": "Lisboa",
    "Ponte 25 de Abril": "Lisboa",
    "Sé de Lisboa": "Lisboa",
    "Universidade de Coimbra": "Coimbra",
    "Convento de Cristo": "Tomar",
    "Mosteiro de Alcobaça": "Alcobaça",
    "Mosteiro da Batalha": "Batalha",
    "Palácio da Bolsa": "Porto",
    "Sé do Porto": "Porto",
    "Ponte Dom Luís I": "Porto",
    "Santuário do Bom Jesus do Monte": "Braga",
    "Castelo de Guimarães": "Guimarães",
    "Torre dos Clérigos": "Porto",
    "Aqueduto das Águas Livres": "Lisboa",
    "Palácio Nacional de Mafra": "Mafra",
    "Palácio Nacional de Sintra": "Sintra",
    "Castelo de Almourol": "Vila Nova da Barquinha",
    "Castelo de Óbidos": "Óbidos",
    "Fortaleza de Sagres": "Sagres",
    "Sé de Braga": "Braga",
    "Ruínas de Conímbriga": "Condeixa-a-Nova",
    "Templo Romano de Évora": "Évora",
}
