"""Portuguese monuments and landmarks."""

MONUMENTOS = [
    "Torre de Belém",
    "Mosteiro dos Jerónimos",
    "Palácio da Pena",
    "Castelo de São Jorge",
    "Ponte 25 de Abril",
    "Sé de Lisboa",
    "Universidade de Coimbra",
    "Convento de Cristo",
    "Mosteiro de Alcobaça",
    "Mosteiro da Batalha",
    "Palácio da Bolsa",
    "Sé do Porto",
    "Ponte Dom Luís I",
    "Santuário do Bom Jesus do Monte",
    "Castelo de Guimarães",
    "Torre dos Clérigos",
    "Aqueduto das Águas Livres",
    "Palácio Nacional de Mafra",
    "Palácio Nacional de Sintra",
    "Castelo de Almourol",
    "Castelo de Óbidos",
    "Fortaleza de Sagres",
    "Sé de Braga",
    "Ruínas de Conímbriga",
    "Templo Romano de Évora",
]

# Map Portuguese names to English Wikipedia article titles
WIKIPEDIA = {
    "Torre de Belém": "Belém Tower",
    "Mosteiro dos Jerónimos": "Jerónimos Monastery",
    "Palácio da Pena": "Pena Palace",
    "Castelo de São Jorge": "São Jorge Castle",
    "Ponte 25 de Abril": "25 de Abril Bridge",
    "Sé de Lisboa": "Lisbon Cathedral",
    "Universidade de Coimbra": "University of Coimbra",
    "Convento de Cristo": "Convent of Christ (Tomar)",
    "Mosteiro de Alcobaça": "Alcobaça Monastery",
    "Mosteiro da Batalha": "Batalha Monastery",
    "Palácio da Bolsa": "Palácio da Bolsa",
    "Sé do Porto": "Porto Cathedral",
    "Ponte Dom Luís I": "Dom Luís I Bridge",
    "Santuário do Bom Jesus do Monte": "Bom Jesus do Monte",
    "Castelo de Guimarães": "Guimarães Castle",
    "Torre dos Clérigos": "Clérigos Tower",
    "Aqueduto das Águas Livres": "Águas Livres Aqueduct",
    "Palácio Nacional de Mafra": "Palace of Mafra",
    "Palácio Nacional de Sintra": "Palace of Sintra",
    "Castelo de Almourol": "Almourol Castle",
    "Castelo de Óbidos": "Castle of Óbidos",
    "Fortaleza de Sagres": "Fortress of Sagres",
    "Sé de Braga": "Braga Cathedral",
    "Ruínas de Conímbriga": "Conímbriga",
    "Templo Romano de Évora": "Temple of Diana (Évora)",
}

LOCALIZACOES = {
    "Torre de Belém": "Lisboa",
    "Mosteiro dos Jerónimos": "Lisboa",
    "Palácio da Pena": "Sintra",
    "Castelo de São Jorge": "Lisboa",
    "Ponte 25 de Abril": "Lisboa",
    "Sé de Lisboa": "Lisboa",
    "Universidade de Coimbra": "Coimbra",
    "Convento de Cristo": "Tomar",
    "Mosteiro de Alcobaça": "Alcobaça",
    "Mosteiro da Batalha": "Batalha",
    "Palácio da Bolsa": "Porto",
    "Sé do Porto": "Porto",
    "Ponte Dom Luís I": "Porto",
    "Santuário do Bom Jesus do Monte": "Braga",
    "Castelo de Guimarães": "Guimarães",
    "Torre dos Clérigos": "Porto",
    "Aqueduto das Águas Livres": "Lisboa",
    "Palácio Nacional de Mafra": "Mafra",
    "Palácio Nacional de Sintra": "Sintra",
    "Castelo de Almourol": "Vila Nova da Barquinha",
    "Castelo de Óbidos": "Óbidos",
    "Fortaleza de Sagres": "Sagres",
    "Sé de Braga": "Braga",
    "Ruínas de Conímbriga": "Condeixa-a-Nova",
    "Templo Romano de Évora": "Évora",
}
